### ISSUE TITLE
Window comes up in not default state

### ISSUE THREAD

**Issue by gnuarm** [ericpromislow/tabhunter#112]
First let me say thanks for this add on.  I use it all the time.  

However, when it brings a window up with a tab I was looking for, the window is not visible.  Normally I maximize my browser windows.  The window I am in is no longer foreground, but nothing else is visible.  I have to flip to the previous window with alt-tab and then flip back to the new window with alt-tab to see it.  Even then it is not maximized.  

Is this my installation or something with the way tabhunter works?  I do typically have hundreds of tabs open in dozens of windows.  I'm trying to work on that getting rid of the tabs I don't need open anymore, but that's actually a fair amount of work, lol.

**Comment by gnuarm** [comment]
Now I have another tab open for this report.  lol

**Comment by ericpromislow** [comment]
Actually I've noticed this lately as well in firefox, this looks like a legitimate bug.

Under the "More" option there's a thing to help you bulk-bookmark tabs and then delete them. Which just swaps one problem for another. I recently had a look at all my bookmarks from the 2006, '07, and '08 folders, and almost all of them 404ed.

**Comment by ericpromislow** [comment]
And now I can't repro. The code looks good. Next time this happens, could you bring up the web console and look for an error message? I emit them whenever there's a problem bringing up the current window. But this looks like a firefox problem.

**Comment by ericpromislow** [comment]
It just happened, with a beep beforehand. Nothing in the web console though. Before I file a moz bug, when I'm off work I'll try adding a little bit of that setTimeout magic.

**Comment by gnuarm** [comment]
Now that I know to turn off the audio setting, I won't see this issue.  It only happens when the audio only setting is left on.

**Comment by gnuarm** [comment]
I still see the tool bring up windows in the non-maximized state.  I always have my browser windows maximized.  When tabhunter brings up a target window, it is not maximized but more importantly it is not visible.  I have to switch to another window, then back to make it visible.  Any idea what's up with that?

**Comment by ericpromislow** [comment]
Which OS+version and browser+version?

**Comment by gnuarm** [comment]
Firefox 86.0.1 (64-bit), Win10 - Don't know how to get the version.

**Comment by gnuarm** [comment]
Is it supposed to bring the window up without changing the window size?

**Comment by ericpromislow** [comment]
Just looked at the code -- when it brings up the window, it brings it up as "normal". This is because if the window was minimized, not specifying 'normal' would leave it minimized, which isn't very helpful.

So yeah, it should only do that if it's necessary.

**Comment by gnuarm** [comment]
Something is wrong.  First, all my windows are either maximized or minimized with the same result in either case.  What I see is the window that was foreground is still visible, but now does not have focus as indicated by the title bar color.  No other window is visible.  The window that is newly selected and should have focus is not visible.  

To make that newly selected window appear requires switching between windows and back.  I usually use alt-tab twice to switch back to the original window then back to the new window.  Now the new window, which had been maximized, is now "normal" size which is often half off the screen and inconvenient to access. 

When a window is maximized and the user minimizes it, selecting that window by any other means (such as selecting it in the task bar or using alt-tab) brings it to the foreground maximized.  Obviously this is possible and is the preferred way to handle the matter.  

Now that I understand not to use the audio only feature, this is the only remaining problem with using tab hunter.  I hope this can be fixed.  It is a great program for us tab collectors.

**Comment by ericpromislow** [comment]
Fixed the non-maximizing in version 3.3.0, now up for firefox& chrome. I also see that on macos, firefox can't find a maximized window, but chrome can. Will assume that because windows doesn't use virtual desktops, should be no problem.

**Comment by gnuarm** [comment]
That's pretty good.  Thanks.  The selected window still does not show in the foreground.  The window the selection was made from is still visible, but not the foreground window.  The window selected is not visible at all.  I still have to alt-tab between them or minimize the window I don't want to see.   Any ideas on why that is happening?

**Comment by ericpromislow** [comment]
Hmm... I'll pull the `drawAttention: true` field off the `updateInfo` block when I call `browser.windows.update`  

I'm specifying both `drawAttention` and `focused` and they seem to conflict. Possibly firefox favors `drawAttention` while chrome favors `focused`

**Comment by ericpromislow** [comment]
It looks like chrome and firefox behave differently here. This will take a while.
